copyright: Copyright &copy; 2024 - Florian Schuttkowski
site_name: FlorianSchuttkowski
site_url: https://mydomain.org/mysite
theme:
  name: material
  language: de
  icon:
    logo: material/brain
  font:
    text: Spectral
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Zum hellen Modus wechseln

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Zum dunklen Modus wechseln

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Farbvorgabe des Systems anwenden

  features:
    - navigation.tracking
    - navigation.footer
    - navigation.tabs

plugins:
  - search
  - blog
  - tags:
      tags_file: tags.md
  - privacy
  - social

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk