copyright: Copyright &copy; 2024 - Florian Schuttkowski
site_name: FlorianSchuttkowski
site_url: https://mydomain.org/mysite

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

theme:
  name: material
  language: de
  icon:
    logo: material/brain
  font:
    text: Spectral
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Zum hellen Modus wechseln

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Zum dunklen Modus wechseln

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Farbvorgabe des Systems anwenden

  features:
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.select

plugins:
  - search
  - blog
  - tags:
      tags_file: tags.md
  - privacy
  - social
  - glightbox

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk

markdown_extensions:
  - abbr # Tooltips
  - admonition # Callouts (mega)
  - attr_list # HTML Klassen, braucht zB lazy loading
  - md_in_html # markdown und html mischen
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
    - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
    - custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets

